### ISSUE TITLE
Incorrect markdown escape in multiple-tickets rich embed

### ISSUE THREAD

**Issue by MrDodojo** [mojira/mojira-discord-bot#184] opened 2021-04-12 07:08 UTC
## The Bug

A multiple-tickets rich embed with a title that includes markdown has visible markdown escapes.

Introduced by #160

This only occurs on my phone(Android), not on my laptop(Windows). Looks like Android(my Android phone) does not support markdown in hyperlinks in a rich embed description while Windows does. This means it is not possible to completely fix this with a change to the bot. Best solution would be to only add markdown escapes to valid markdown, instead of all markdown symbols like currently.

## Example

![Screenshot_20210412-084738_Discord](https://user-images.githubusercontent.com/47711280/114354375-71a0bf00-9b6e-11eb-9da9-04e0798900e0.jpg)
^ this would not be valid markdown, yet backslashes are still added. 

## Expected behavior

No visible markdown escapes or markdown escapes only added to valid markdown which will decrease the cases of this issue occuring.

**Comment by violine1101** [comment] 2021-04-12 10:32
This is actually an issue with Mobile Discord since it uses a completely different escaping algorithm than Discord. However this is still something we should and I'd like to fix. Fix should be fairly straightforward.

**Comment by chandler05** [comment] 2021-05-04 23:04
Can you still reproduce this in Mobile Discord? I can no longer reproduce on Android when I could before.

**Comment by violine1101** [comment] 2021-05-05 07:21
Even if it's fixed on Discord's side, it'd still be good if we wouldn't reimplement this but use discord.js's provided escaping function instead. So please leave this open for now anyway.

**Comment by chandler05** [comment] 2021-05-07 10:27
Just experienced this again, so I guess it's not actually fixed.

**Closed** 2021-05-12 09:44 UTC
Labels: bug
