### ISSUE TITLE
Java Fix feed doesn't work for report that already had a fix version

### ISSUE THREAD

**Issue by Jack-McKalling** [mojira/mojira-discord-bot#187] opened 2021-04-28 14:34 UTC
## The Bug
When a report like gets resolved as fixed, it isn't announced in the channel if it already had a fix version.

## Example
For example https://bugs.mojang.com/browse/MC-219155. By the time the report was fixed for 21w17a, it already had 21w11a as the fix version.

## Expected behavior
Each time a report receives a fix version, it should get mentioned in the channel, not only for the first time the issue was fixed.

**Comment by chandler05** [comment] 2021-04-28 14:37
Duplicate of #88

**Closed** 2021-04-28 14:37 UTC
Labels: bug
